url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Freelance Web Designer Silicon Valley" # the name of your site, e.g. ACME Corp.
sitebar: Hey There. I am a Freelance Web Designer experienced in WordPress, User Interface Design, JavaScript or Social Media Marketing. You can check out my Services right here. Web Design Silicon Valley