url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Freelance Web Designer Silicon Valley" # the name of your site, e.g. ACME Corp.
description: My Name is Lukasz Adam and I work as a Freelance Web Designer. I've created a lot of pages in Silicon Valley and I can help you if you need design, development or SEO.
sidebar_text_1: As a Freelance Web Designer I'm experienced in WordPress, User Interface Design, JavaScript and Social Media Marketing. You can check out my Services right here.